// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "5d6a71db-8232-4543-b56f-1bc421cb20a8");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1655470138);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1655470110);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1655470109);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1655470258);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1655470168);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{9cbe5208-8cd8-4b0c-a299-39e36f64ed34}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1655470108);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 127);
user_pref("browser.newtabpage.activity-stream.impressionId", "{048c22d9-d516-48f2-832f-5ea57f49bc45}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1655470109);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1655470115366");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1655471942366");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1655470110402");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1655491710402");
user_pref("browser.search.region", "FI");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1655470109");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220609170544");
user_pref("browser.startup.homepage_override.mstone", "101.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1655470109);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1655470109346");
user_pref("distribution.Manjaro.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "101.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "FI");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "a78a832e487048af9110cdc5309e0323");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220609170544");
user_pref("extensions.lastAppVersion", "101.0.1");
user_pref("extensions.lastPlatformVersion", "101.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"0131d763-3560-4290-97a5-cd8665cb1e2f\",\"formautofill@mozilla.org\":\"d1916824-aaf8-4c76-aca7-c33b1ca5fffa\",\"pictureinpicture@mozilla.org\":\"ba682adc-44cc-4563-8d8e-6a2dc2e89e92\",\"screenshots@mozilla.org\":\"12f9e3df-f72a-4592-b469-89fe9579be08\",\"webcompat-reporter@mozilla.org\":\"98c6fc61-38c5-41bf-b303-9d1323d01234\",\"webcompat@mozilla.org\":\"9108bdbe-bdae-4274-8bad-d9c387669b76\",\"default-theme@mozilla.org\":\"b95bab79-20ab-46db-97d7-76663550218c\",\"addons-search-detection@mozilla.com\":\"af7bcdf5-4696-45bb-a334-3c0f946a6ea4\",\"google@search.mozilla.org\":\"50580c1b-6497-41f5-8bce-bdf9b865f4e6\",\"amazondotcom@search.mozilla.org\":\"3569bf6d-691e-4900-ac1b-e1b1f09ed818\",\"wikipedia@search.mozilla.org\":\"66b51d87-b264-4e6d-b7bb-46faaabc6687\",\"bing@search.mozilla.org\":\"c3fda925-4687-490e-b29c-5e1d5c7fcd9d\",\"ddg@search.mozilla.org\":\"e9284895-eb4d-49f7-b5f5-f2a1bd25463c\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1655470109);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ab5bf80a-faa4-488c-94b2-fe92aafe436a");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1655470107);
user_pref("toolkit.telemetry.cachedClientID", "a4fb36f9-4006-42b2-83a0-34b54acccd66");
user_pref("toolkit.telemetry.previousBuildID", "20220609170544");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
