window.merchants = {
	"2game":{
		"name":"2game",
		"websiteUrl":"https://2game.com/"
	},
	"allyouplay":{
		"name":"Allyouplay",
		"websiteUrl":"https://www.allyouplay.com/"
	},
	"amazon":{
		"name":"Amazon",
		"websiteUrl":"https://www.amazon.fr/"
	},
	"buygames":{
		"name":"BuyGames",
		"websiteUrl":"https://www.buygames.ps/"
	},
/*	"CDKeys":{
		"name":"CDKeys",
		"websiteUrl":"https://www.cdkeys.com/"
	},*/
	"eneba":{
		"name":"Eneba",
		"websiteUrl":"https://www.eneba.com/"
	},
	"epicgames":{
		"name":"Epic Games",
		"websiteUrl":"https://www.epicgames.com"
	},
	"g2a":{
		"name":"G2A",
		"websiteUrl":"https://www.g2a.com"
	},
	"g2play":{
		"name":"G2Play",
		"websiteUrl":"https://www.g2play.net"
	},
	"gamebillet":{
		"name":"GameBillet",
		"websiteUrl":"https://www.gamebillet.com"
	},
	"gameblog":{
		"name":"GameBlog",
		"websiteUrl":"https://www.gameblog.fr"
	},
	"gamekult":{
		"name":"GameKult",
		"websiteUrl":"https://www.gamekult.com"
	},
	"gamesforplay":{
		"name":"GamesForPlay",
		"websiteUrl":"https://gamesforplay.com/"
	},
	"gamersgate":{
		"name":"GamersGate",
		"websiteUrl":"https://www.gamersgate.com"
	},
	"gamesplanet":{
		"name":"GamesPlanet",
		"websiteUrl":"https://www.gamesplanet.com"
	},
	"gamespot":{
		"name":"GameSpot",
		"websiteUrl":"https://www.gamespot.com"
	},
	"gamivo":{
		"name":"Gamivo",
		"websiteUrl":"https://www.gamivo.com"
	},
	"gocdkeys":{
		"name":"GoCdkeys",
		"websiteUrl":"https://gocdkeys.com/"
	},
	"gog":{
		"name":"GoG",
		"websiteUrl":"https://www.gog.com"
	},
	"greenmangaming":{
		"name":"GreenManGaming",
		"websiteUrl":"https://www.greenmangaming.com/"
	},
	"gvgmall":{
		"name":"GVGmall",
		"websiteUrl":"https://www.gvgmall.com/"
	},
	"hrk":{
		"name":"HRK",
		"websiteUrl":"https://www.hrkgame.com"
	},
	"humblebundle":{
		"name":"HumbleBundle",
		"websiteUrl":"https://www.humblebundle.com/"
	},
	"instantgaming":{
		"name":"InstantGaming",
		"websiteUrl":"https://www.instant-gaming.com/"
	},
	"jeuxvideocom":{
		"name":"JeuxVideoCom",
		"websiteUrl":"https://www.jeuxvideo.com/"
	},
	"k4g":{
		"name":"K4g",
		"websiteUrl":"https://k4g.com/"
	},
	"kinguin":{
		"name":"Kinguin",
		"websiteUrl":"https://www.kinguin.net/"
	},
	"microsoft":{
		"name":"Microsoft",
		"websiteUrl":"https://www.microsoft.com"
	},
	"nintendo":{
		"name":"Nintendo",
		"websiteUrl":"https://www.nintendo.com/"
	},
	"origin":{
		"name":"Origin",
		"websiteUrl":"https://www.origin.com"
	},
	"pixelcodes":{
		"name":"Pixelcodes",
		"websiteUrl":"https://pixelcodes.com"
	},
	"playstation":{
		"name":"Playstation",
		"websiteUrl":"https://store.playstation.com/"
	},
	"premiumCDKeys":{
		"name":"PremiumCDKeys",
		"websiteUrl":"https://www.premiumcdkeys.com"
	},
	"punktid":{
		"name":"Punktid",
		"websiteUrl":"https://punktid.com"
	},
	"royalcdkeys":{
		"name":"Royalcdkeys",
		"websiteUrl":"https://royalcdkeys.com"
	},
	"scdkey":{
		"name":"SCDKey",
		"websiteUrl":"https://www.scdkey.com"
	},
	"steam":{
		"name":"Steam",
		"websiteUrl":"https://www.steampowered.com"
	},
	"twitch":{
		"name":"Twitch",
		"websiteUrl":"https://www.twitch.tv"
	},
	"ubisoft":{
		"name":"Ubisoft",
		"websiteUrl":"https://store.ubi.com"
	},
	"voidu":{
		"name":"Voidu",
		"websiteUrl":"https://www.voidu.com"
	},
	"xbox":{
		"name":"Xbox",
		"websiteUrl":"https://www.xbox.com/"
	},
	"youtube":{
		"name":"Youtube",
		"websiteUrl":"https://www.youtube.com"
	}
}