# cct
# Autogenerated from man page /usr/share/man/man1/cct.1.gz
complete -c cct -s c -d 'Specify input columns for (up to) 4 input parameters.  Defaults to 1,2,3,4'
complete -c cct -s d -d 'New in version 5. 2. 0. sp Specify the number of decimals in the output'
complete -c cct -s I -d 'Do the inverse transformation. UNINDENT NDENT 0. 0'
complete -c cct -s o -l output -d 'Specify the name of the output file. UNINDENT NDENT 0. 0'
complete -c cct -s t -l time -d 'Specify a fixed observation time to be used for all input data'
complete -c cct -s z -l height -d 'Specify a fixed observation height to be used for all input data'
complete -c cct -s s -l skip-lines -d 'New in version 5. 1. 0. sp Skip the first n lines of input'
complete -c cct -s v -l verbose -d 'Write non-essential, but potentially useful, information to stderr'
complete -c cct -l version -d 'Print version number'

