# dcmodify
# Autogenerated from man page /usr/share/man/man1/dcmodify.1.gz
complete -c dcmodify -s i -l insert -d '       dcmodify -i "(0010,0010)=A Name" file'
complete -c dcmodify -o if -l insert-from-file -d '       dcmodify -if "PixelData=pixel. raw" file'
complete -c dcmodify -s m -l modify -d '       dcmodify -m "(0010,0010)=A Name" file'
complete -c dcmodify -o mf -l modify-from-file -d '       dcmodify -mf "PixelData=pixel. raw" file'
complete -c dcmodify -o ma -l modify-all -d '       dcmodify -ma "(0010,0010)=New Name" file'
complete -c dcmodify -s e -l erase -d '       dcmodify -e "(0010,0010)" *'
complete -c dcmodify -o ea -l erase-all -d '       dcmodify -ea "(0010,0010)" *'
complete -c dcmodify -o ep -l erase-private -d '       dcmodify -ep *. dcm        Deletes all private tags (i. e'
complete -c dcmodify -o gst -l gen-stud-uid -d '       dcmodify -gst file'
complete -c dcmodify -o gse -l gen-ser-uid -d '       dcmodify -gse file'
complete -c dcmodify -o gin -l gen-inst-uid -d '       dcmodify -gin file'
complete -c dcmodify -o nmu -l no-meta-uid -d '       dcmodify -m "SOPInstanceUID=[UID]" -nmu *'

