# dcmqrti
# Autogenerated from man page /usr/share/man/man1/dcmqrti.1.gz
complete -c dcmqrti -l ---------------------------------------------------------- -d 'Command Summary: help                list this summary ?                   sh…'

