# fsc
# Autogenerated from man page /usr/share/man/man1/fsc.1.gz
complete -c fsc -o reset -d 'Reset compile server caches'
complete -c fsc -o shutdown -d 'Shut down the compilation daemon'
complete -c fsc -o server -d 'Specify compile server host at port number'
complete -c fsc -o 'J<flag>' -d 'Pass <flag> directly to the Java VM for the compilation daemon.  DESCRIPTION'

