# gie
# Autogenerated from man page /usr/share/man/man1/gie.1.gz
complete -c gie -s h -l help -d 'Print usage information . UNINDENT NDENT 0. 0'
complete -c gie -s o -l output -d 'Specify output file name . UNINDENT NDENT 0. 0'
complete -c gie -s v -l verbose -d 'Verbose: Provide non-essential informational output'
complete -c gie -s q -l quiet -d 'Quiet: Opposite of verbose.  In quiet mode not even errors are reported'
complete -c gie -s l -l list -d 'List the PROJ internal system error codes . UNINDENT NDENT 0. 0'
complete -c gie -l version -d 'Print version number Tests for gie are defined in simple text files'
complete -c gie -l ------------------------------------------ -d 'Test output of the UTM projection'
complete -c gie -l ----------------------------------------------------------------------------- -d 'Reading file \'test. gie\' ** Mercator projection test **'
complete -c gie -l ----------------------------------------------- -d '# A command on several lines must use " \\" continuation operation proj=hgrids…'

