# gpmetis
# Autogenerated from man page /usr/share/man/man1/gpmetis.1.gz
complete -c gpmetis -o ptype -d 'Specifies the scheme to be used for computing the k-way partitioning'
complete -c gpmetis -o ctype -d 'Specifies the scheme to be used to match the vertices of the graph during the…'
complete -c gpmetis -o iptype -d 'Specifies the scheme to be used to compute the initial partitioning of the gr…'
complete -c gpmetis -o objtype -d 'Specifies the objective that the partitioning routines will optimize'
complete -c gpmetis -o no2hop -d 'Specifies that the coarsening will not perform any 2-hop matchings when the s…'
complete -c gpmetis -o contig -d 'Specifies that the partitioning routines should try to produce partitions tha…'
complete -c gpmetis -o minconn -d 'Specifies that the partitioning routines should try to minimize the maximum d…'
complete -c gpmetis -o tpwgts -d 'Specifies the name of the file that stores the target weights for each partit…'
complete -c gpmetis -o ufactor -d 'Specifies the maximum allowed load imbalance among the partitions'
complete -c gpmetis -o ubvec -d 'Applies only for multi-constraint partitioning and specifies the per constrai…'
complete -c gpmetis -o niter -d 'Specifies the number of iterations for the refinement algorithms at each stag…'
complete -c gpmetis -o ncuts -d 'Specifies the number of different partitionings that it will compute'
complete -c gpmetis -o nooutput -d 'Specifies that no partitioning file should be generated'
complete -c gpmetis -o seed -d 'Selects the seed of the random number generator'
complete -c gpmetis -o dbglvl -d 'Selects the dbglvl'
complete -c gpmetis -o help -d 'Prints this message'

