# hexedit
# Autogenerated from man page /usr/share/man/man1/hexedit.1.gz
complete -c hexedit -s s -l sector -d 'Format the display to have entire sectors'
complete -c hexedit -s m -l maximize -d 'Try to maximize the display'
complete -c hexedit -l color -d 'Display colors'
complete -c hexedit -o 'l<n>' -l linelength -d 'Explicitly set the number of bytes to display per line to <n>'
complete -c hexedit -s h -l help -d 'Show the usage.  COMMANDS (quickly) Moving'

