# hivexregedit
# Autogenerated from man page /usr/share/man/man1/hivexregedit.1.gz
complete -c hivexregedit -l help -d 'Display help'
complete -c hivexregedit -l debug -d 'Enable debugging in the hivex library'
complete -c hivexregedit -l merge -d 'Vb 2  hivexregedit --merge [--prefix prefix] [--encoding enc]           hivef…'
complete -c hivexregedit -l export -d 'Vb 1  hivexregedit --export [--prefix prefix] hivefile key > regfile . Ve '
complete -c hivexregedit -l prefix -d 'Hive files and Windows Registry key names are indirectly related'
complete -c hivexregedit -l encoding -d 'When merging (only), you may need to specify the encoding for strings to be u…'
complete -c hivexregedit -l unsafe-printable-strings -d 'When exporting (only), assume strings are \\s-1UTF-16LE\\s0 and print them as s…'
complete -c hivexregedit -l unsafe -d 'Use heuristics to tolerate certain levels of corruption within hives'

