# listgeo
# Autogenerated from man page /usr/share/man/man1/listgeo.1.gz
complete -c listgeo -s d -d 'report lat/long corners in decimal degrees instead of DMS'
complete -c listgeo -o tfw -d 'Generate a . tfw (ESRI TIFF World) file for the target file'
complete -c listgeo -o no-norm -d 'Don\'t report \'normalized\' parameter values'
complete -c listgeo -o proj4 -d 'Report PROJ. 4 equivelent projection definition'
complete -c listgeo -s t -d 'force to look in DIR for EPSG_CVS files, overriding default behaviour'

