# lsmdev
# Autogenerated from man page /usr/share/man/man8/lsmdev.8.gz
complete -c lsmdev -l addattr
complete -c lsmdev -s a -l auto
complete -c lsmdev -s d -l defined
complete -c lsmdev -l delattr
complete -c lsmdev -l dumpjson
complete -c lsmdev -s i -l index
complete -c lsmdev -l jsonfile
complete -c lsmdev -s m -l manual
complete -c lsmdev -s p -l parent
complete -c lsmdev -s t -l type
complete -c lsmdev -s u -l uuid
complete -c lsmdev -l value
complete -c lsmdev -s v -l verbose
complete -c lsmdev -s V -l version
complete -c lsmdev -s s
complete -c lsmdev -s e

