# m2gmetis
# Autogenerated from man page /usr/share/man/man1/m2gmetis.1.gz
complete -c m2gmetis -o gtype -d 'Specifies the graph that will be generated.  The possible values are:'
complete -c m2gmetis -o ncommon -d 'Specifies the common number of nodes that two elements must have in order to …'
complete -c m2gmetis -o dbglvl -d 'Selects the dbglvl'
complete -c m2gmetis -o help -d 'Prints this message'

