# mdevctl
# Autogenerated from man page /usr/share/man/man8/mdevctl.8.gz
complete -c mdevctl -l addattr
complete -c mdevctl -s a -l auto
complete -c mdevctl -s d -l defined
complete -c mdevctl -l delattr
complete -c mdevctl -l dumpjson
complete -c mdevctl -s i -l index
complete -c mdevctl -l jsonfile
complete -c mdevctl -s m -l manual
complete -c mdevctl -s p -l parent
complete -c mdevctl -s t -l type
complete -c mdevctl -s u -l uuid
complete -c mdevctl -l value
complete -c mdevctl -s v -l verbose
complete -c mdevctl -s V -l version
complete -c mdevctl -s s
complete -c mdevctl -s e

