# microsoft-edge-stable
# Autogenerated from man page /usr/share/man/man1/microsoft-edge-stable.1.gz
complete -c microsoft-edge-stable -l user-data-dir -d 'Specifies the directory that user data (your "profile") is kept in'
complete -c microsoft-edge-stable -l inprivate -d 'Open in InPrivate mode'
complete -c microsoft-edge-stable -l new-window -d 'If PATH or URL is given, open it in a new window'
complete -c microsoft-edge-stable -l proxy-server -d 'Specify the HTTP/SOCKS4/SOCKS5 proxy server to use for requests'
complete -c microsoft-edge-stable -l no-proxy-server -d 'Disables the proxy server'
complete -c microsoft-edge-stable -l proxy-auto-detect -d 'Autodetect proxy configuration'
complete -c microsoft-edge-stable -l proxy-pac-url -d 'Specify proxy autoconfiguration URL'
complete -c microsoft-edge-stable -l password-store -d 'Set the password store to use'
complete -c microsoft-edge-stable -l version -d 'Show version information'
complete -c microsoft-edge-stable -l display -d 'See the GTK documentation for more: <http://library. gnome'

