# mpmetis
# Autogenerated from man page /usr/share/man/man1/mpmetis.1.gz
complete -c mpmetis -o gtype -d 'Specifies the graph to be used for computing the partitioning The possible va…'
complete -c mpmetis -o ptype -d 'Specifies the scheme to be used for computing the k-way partitioning'
complete -c mpmetis -o ctype -d 'Specifies the scheme to be used to match the vertices of the graph during the…'
complete -c mpmetis -o iptype -d 'Specifies the scheme to be used to compute the initial partitioning of the gr…'
complete -c mpmetis -o objtype -d 'Specifies the objective that the partitioning routines will optimize'
complete -c mpmetis -o contig -d 'Specifies that the partitioning routines should try to produce partitions tha…'
complete -c mpmetis -o minconn -d 'Specifies that the partitioning routines should try to minimize the maximum d…'
complete -c mpmetis -o tpwgts -d 'Specifies the name of the file that stores the target weights for each partit…'
complete -c mpmetis -o ufactor -d 'Specifies the maximum allowed load imbalance among the partitions'
complete -c mpmetis -o ncommon -d 'Specifies the common number of nodes that two elements must have in order to …'
complete -c mpmetis -o niter -d 'Specifies the number of iterations for the refinement algorithms at each stag…'
complete -c mpmetis -o ncuts -d 'Specifies the number of different partitionings that it will compute'
complete -c mpmetis -o nooutput -d 'Specifies that no partitioning file should be generated'
complete -c mpmetis -o seed -d 'Selects the seed of the random number generator'
complete -c mpmetis -o dbglvl -d 'Selects the dbglvl'
complete -c mpmetis -o help -d 'Prints this message'

