# ndmetis
# Autogenerated from man page /usr/share/man/man1/ndmetis.1.gz
complete -c ndmetis -o ctype -d 'Specifies the scheme to be used to match the vertices of the graph during the…'
complete -c ndmetis -o iptype -o ptype -d 'Specifies the scheme to be used to compute the initial bisection of the graph'
complete -c ndmetis -o rtype -d 'Specifies the scheme to be used for refinement.  The possible values are:'
complete -c ndmetis -o ufactor -d 'Specifies the maximum allowed load imbalance between the left and right parti…'
complete -c ndmetis -o pfactor -d 'Specifies the minimum degree of the vertices that will be ordered last'
complete -c ndmetis -o no2hop -d 'Specifies that the coarsening will not perform any 2-hop matchings when the s…'
complete -c ndmetis -o nocompress -d 'Specifies that the graph should not be compressed by combining together verti…'
complete -c ndmetis -o ccorder -d 'Specifies if the connected components of the graph should first be identified…'
complete -c ndmetis -o niter -d 'Specifies the maximum number of iterations for the refinement algorithms at e…'
complete -c ndmetis -o nseps -d 'Specifies the number of different separators that it will compute at each lev…'
complete -c ndmetis -o nooutput -d 'Specifies that no ordering file should be generated'
complete -c ndmetis -o seed -d 'Selects the seed of the random number generator'
complete -c ndmetis -o dbglvl -d 'Selects the dbglvl'
complete -c ndmetis -o help -d 'Prints this message'

