# osk-sdl
# Autogenerated from man page /usr/share/man/man1/osk-sdl.1.gz
complete -c osk-sdl -s d -d 'Decrypt this disk.  This argument is mandatory unless -t is used'
complete -c osk-sdl -s n -d 'Name of the decrypted disk'
complete -c osk-sdl -s c -d 'Locaton of the osk-sdl config file.  Defaults to "/etc/osk. conf"'
complete -c osk-sdl -s o -d 'Locaton of the osk-sdl config override file'
complete -c osk-sdl -s v -l verbose -d 'Enable verbose output'
complete -c osk-sdl -s k -l keyscript -d 'Enable keyscript mode'
complete -c osk-sdl -s G -l no-gles -d 'Do not use OpenGL ES driver unless it is the default driver'
complete -c osk-sdl -s x -l no-keyboard -d 'Do not display the keyboard, only the input box'

