# podman-play-kube
# Autogenerated from man page /usr/share/man/man1/podman-play-kube.1.gz
complete -c podman-play-kube -l - -d 'apiVersion: v1 kind: Pod metadata:   name: foobar spec:   containers:   - com…'
complete -c podman-play-kube -l annotation
complete -c podman-play-kube -l authfile
complete -c podman-play-kube -l build
complete -c podman-play-kube -l cert-dir
complete -c podman-play-kube -l configmap
complete -c podman-play-kube -l context-dir
complete -c podman-play-kube -l creds
complete -c podman-play-kube -l down
complete -c podman-play-kube -l help -s h
complete -c podman-play-kube -l ip
complete -c podman-play-kube -l log-driver
complete -c podman-play-kube -l log-opt
complete -c podman-play-kube -l mac-address
complete -c podman-play-kube -l network -l net
complete -c podman-play-kube -l no-hosts
complete -c podman-play-kube -l quiet -s q
complete -c podman-play-kube -l replace
complete -c podman-play-kube -l seccomp-profile-root
complete -c podman-play-kube -l start
complete -c podman-play-kube -l tls-verify

