# scaladoc
# Autogenerated from man page /usr/share/man/man1/scaladoc.1.gz
complete -c scaladoc -s d -d 'Specify where to generate documentation'
complete -c scaladoc -o version -d 'Print product version and exit'
complete -c scaladoc -o help -d 'Print a synopsis of available options. \\" '
complete -c scaladoc -o doc-title -d 'Define the overall title of the documentation, typically the name of the libr…'
complete -c scaladoc -o doc-version -d 'Define the overall version number of the documentation, typically the version…'
complete -c scaladoc -o doc-source-url -d 'Define a URL to be concatenated with source locations for link to source files'
complete -c scaladoc -o doc-external-doc -d 'Define a comma-separated list of classpath_entry_path#doc_URL pairs describin…'
complete -c scaladoc -o jdk-api-doc-base -d 'Define a URL to be concatenated with source locations for link to Java API'
complete -c scaladoc -o verbose -d 'Output messages about what the compiler is doing'
complete -c scaladoc -o deprecation -d 'Indicate whether source should be compiled with deprecation information; defa…'
complete -c scaladoc -o classpath -d 'Specify where to find user class files (on Unix-based systems a colon-separat…'
complete -c scaladoc -o sourcepath -d 'Specify where to find input source files'
complete -c scaladoc -o bootclasspath -d 'Override location of bootstrap class files (where to find the standard built-…'
complete -c scaladoc -o extdirs -d 'Override location of installed extensions'
complete -c scaladoc -o encoding -d 'Specify character encoding used by source files'

