# scalap
# Autogenerated from man page /usr/share/man/man1/scalap.1.gz
complete -c scalap -o help -d 'Display this usage message'
complete -c scalap -o private -d 'Print private definitions'
complete -c scalap -o verbose -d 'Print out additional information'
complete -c scalap -o version -d 'Print product version and exit'
complete -c scalap -o cp -o classpath -d 'Specify where to find user class files'

