# scotch_mord
# Autogenerated from man page /usr/share/man/man1/scotch_mord.1.gz
complete -c scotch_mord -o 'copt' -d 'Choose default ordering strategy according to one or several options among: '
complete -c scotch_mord -s h -d 'Display some help'
complete -c scotch_mord -o 'mmfile' -d 'Save column block mapping data to file mfile'
complete -c scotch_mord -o 'ostrat' -d 'Use sequential mesh ordering strategy strat (see Scotch user\'s manual for mor…'
complete -c scotch_mord -o 'ttfile' -d 'Save partitioning tree data to file tfile'
complete -c scotch_mord -s V -d 'Display program version and copyright'
complete -c scotch_mord -o 'vverb' -d 'Set verbose mode to verb'

