# scotch_gdump
# Autogenerated from man page /usr/share/man/man1/scotch_gdump.1.gz
complete -c scotch_gdump -o 'bbase' -d 'Set the base value of the graph described by the source code'
complete -c scotch_gdump -s h -d 'Display some help'
complete -c scotch_gdump -o 'pprefix' -d 'Set the prefix to add to to all array names and to the graph buiding function…'
complete -c scotch_gdump -o 'ssuffix' -d 'Set the suffix to add to to all array names and to the graph buiding function…'
complete -c scotch_gdump -s V -d 'Display program version and copyright.  EXAMPLE Create a soure C file \'brol'

