# scotch_gout
# Autogenerated from man page /usr/share/man/man1/scotch_gout.1.gz
complete -c scotch_gout -s h -d 'Display some help'
complete -c scotch_gout -o 'ggeop' -d 'Geometry parameters, which can be an arbitrary combination of any of the foll…'
complete -c scotch_gout -o mn -d 'Do not read mapping data, when it is not available or not required'
complete -c scotch_gout -o 'ooutp' -d 'Select the output file type and allows to provide additional parameters betwe…'
complete -c scotch_gout -s V -d 'Display program version and copyright'

