# scotch_gmap
# Autogenerated from man page /usr/share/man/man1/scotch_gmap.1.gz
complete -c scotch_gmap -o 'bval' -d 'Set maximum load imbalance ratio for graph partitioning or static mapping'
complete -c scotch_gmap -o 'copt' -d 'Choose default mapping strategy according to one or several options among: '
complete -c scotch_gmap -s h -d 'Display some help'
complete -c scotch_gmap -o 'mstrat' -d 'Use sequential mapping strategy strat (see Scotch user\'s manual for more info…'
complete -c scotch_gmap -s q -d '(for gpart)'
complete -c scotch_gmap -o 'qpwght' -d '(for gmap) Use the programs as graph clustering tools instead of static mappi…'
complete -c scotch_gmap -s V -d 'Display program version and copyright'
complete -c scotch_gmap -o 'vverb' -d 'Set verbose mode to verb'

