# scotch_mcv
# Autogenerated from man page /usr/share/man/man1/scotch_mcv.1.gz
complete -c scotch_mcv -s h -d 'Display some help'
complete -c scotch_mcv -o 'iifmt' -d 'Set format of input mesh file, which can be: . RS'
complete -c scotch_mcv -o 'oofmt' -d 'Set format of output mesh file, which can be: . RS'
complete -c scotch_mcv -s V -d 'Display program version and copyright'

