# scotch_amk_ccc
# Autogenerated from man page /usr/share/man/man1/scotch_amk_ccc.1.gz
complete -c scotch_amk_ccc -o 'mmeth' -d 'For amk_m2 only'
complete -c scotch_amk_ccc -s h -d 'Display some help'
complete -c scotch_amk_ccc -s V -d 'Display program version and copyright'

