# scotch_gcv
# Autogenerated from man page /usr/share/man/man1/scotch_gcv.1.gz
complete -c scotch_gcv -s h -d 'Display some help'
complete -c scotch_gcv -o 'iifmt' -d 'Set format of input graph file, which can be: . RS'
complete -c scotch_gcv -o 'oofmt' -d 'Set format of output graph file, which can be: . RS'
complete -c scotch_gcv -s V -d 'Display program version and copyright'

