# scotch_mmk_m2
# Autogenerated from man page /usr/share/man/man1/scotch_mmk_m2.1.gz
complete -c scotch_mmk_m2 -o 'gcfile' -d 'Output graph vertex coordinates (that is, geometry data to be used by gout(1)…'
complete -c scotch_mmk_m2 -s h -d 'Display some help'
complete -c scotch_mmk_m2 -s V -d 'Display program version and copyright'

