# scotch_acpl
# Autogenerated from man page /usr/share/man/man1/scotch_acpl.1.gz
complete -c scotch_acpl -s h -d 'Display some help'
complete -c scotch_acpl -s V -d 'Display program version and copyright'

