# scotch_mtst
# Autogenerated from man page /usr/share/man/man1/scotch_mtst.1.gz
complete -c scotch_mtst -s h -d 'Display some help'
complete -c scotch_mtst -s V -d 'Display program version and copyright'

