# scotch_gbase
# Autogenerated from man page /usr/share/man/man1/scotch_gbase.1.gz
complete -c scotch_gbase -s h -d 'Display some help'
complete -c scotch_gbase -s V -d 'Display program version and copyright.  EXAMPLE Set the base of graph \'brol'

