# scotch_amk_grf
# Autogenerated from man page /usr/share/man/man1/scotch_amk_grf.1.gz
complete -c scotch_amk_grf -o 'bstrat' -d 'Apply bipartitioning strategy strat to compute the recursive bipartition of t…'
complete -c scotch_amk_grf -s h -d 'Display some help'
complete -c scotch_amk_grf -o 'llfile' -d 'Only keep vertices the indices of which belong to the space-separated list st…'
complete -c scotch_amk_grf -s V -d 'Display program version and copyright'

