# scotch_gmk_msh
# Autogenerated from man page /usr/share/man/man1/scotch_gmk_msh.1.gz
complete -c scotch_gmk_msh -s h -d 'Display some help'
complete -c scotch_gmk_msh -s V -d 'Display program version and copyright.  EXAMPLE Create a source graph brol'

