# scotch_gmtst
# Autogenerated from man page /usr/share/man/man1/scotch_gmtst.1.gz
complete -c scotch_gmtst -s h -d 'Display some help'
complete -c scotch_gmtst -s V -d 'Display program version and copyright'

