# scotch_gotst
# Autogenerated from man page /usr/share/man/man1/scotch_gotst.1.gz
complete -c scotch_gotst -s h -d 'Display some help'
complete -c scotch_gotst -s v -d 'Do not account for vertex weights when computing factorization costs'
complete -c scotch_gotst -s V -d 'Display program version and copyright'

