# scotch_gmk_hy
# Autogenerated from man page /usr/share/man/man1/scotch_gmk_hy.1.gz
complete -c scotch_gmk_hy -s b -d 'For gmk_m2 and gmk_m3 only.  Output graphs with base value set to base'
complete -c scotch_gmk_hy -s e -d 'For gmk_m2 only.  Build a 8-neighbor grid rather than a 4-neighbor grid'
complete -c scotch_gmk_hy -o 'gcfile' -d 'For gmk_m2 and gmk_m3 only'
complete -c scotch_gmk_hy -s h -d 'Display some help'
complete -c scotch_gmk_hy -s t -d 'For gmk_m2 and gmk_m3 only'
complete -c scotch_gmk_hy -s V -d 'Display program version and copyright'

