# scotch_atst
# Autogenerated from man page /usr/share/man/man1/scotch_atst.1.gz
complete -c scotch_atst -s h -d 'Display some help'
complete -c scotch_atst -s V -d 'Display program version and copyright'

