# scotch_gtst
# Autogenerated from man page /usr/share/man/man1/scotch_gtst.1.gz
complete -c scotch_gtst -s h -d 'Display some help'
complete -c scotch_gtst -s V -d 'Display program version and copyright'

