# scotch_gord
# Autogenerated from man page /usr/share/man/man1/scotch_gord.1.gz
complete -c scotch_gord -o 'copt' -d 'Choose default ordering strategy according to one or several options among: '
complete -c scotch_gord -s h -d 'Display some help'
complete -c scotch_gord -o 'mmfile' -d 'Save column block mapping data to file mfile'
complete -c scotch_gord -o 'ostrat' -d 'Use sequential graph ordering strategy strat (see Scotch user\'s manual for mo…'
complete -c scotch_gord -o 'ttfile' -d 'Save partitioning tree data to file tfile'
complete -c scotch_gord -s V -d 'Display program version and copyright'
complete -c scotch_gord -o 'vverb' -d 'Set verbose mode to verb'

