# scrub
# Autogenerated from man page /usr/share/man/man1/scrub.1.gz
complete -c scrub -s v -l version -d 'Print scrub version and exit'
complete -c scrub -s r -l remove -d 'Remove the file after scrubbing'
complete -c scrub -s p -l pattern -d 'Select the patterns to write.   See SCRUB METHODS below'
complete -c scrub -s b -l blocksize -d 'Perform read(2) and write(2) calls using the specified blocksize (in bytes)'
complete -c scrub -s f -l force -d 'Scrub even if target contains signature indicating it has already been scrubb…'
complete -c scrub -s S -l no-signature -d 'Do not write scrub signature'
complete -c scrub -s X -l freespace -d 'Create specified directory and fill it with files until  write returns ENOSPC…'
complete -c scrub -s D -l dirent -d 'After scrubbing the file, scrub its name in the directory entry,  then rename…'
complete -c scrub -s s -l device-size -d 'Override the device size (in bytes)'
complete -c scrub -s L -l no-link -d 'If file is a symbolic link, do not scrub the link target'
complete -c scrub -s R -l no-hwrand -d 'Don\'t use a hardware random number generator even if one is available'
complete -c scrub -s t -l no-threads -d 'Don\'t generate random data in parallel with I/O'
complete -c scrub -s n -l dry-run -d 'Do everything but write to targets'
complete -c scrub -s h -l help -d 'Print a summary of command line options on stderr'
complete -c scrub -s E -l extent-only -d 'When scrubbing regular files, scrub only the file extents'

