# sheepfs
# Autogenerated from man page /usr/share/man/man8/sheepfs.8.gz
complete -c sheepfs -s a -l address -d 'specify the sheep address (default: 127. 0. 0. 1)'
complete -c sheepfs -s d -l debug -d 'enable debug output (implies -f)'
complete -c sheepfs -s f -l foreground -d 'sheepfs run in the foreground'
complete -c sheepfs -s k -l pagecache -d 'use local kernel\'s page cache to access volume'
complete -c sheepfs -s o -l objectcache -d 'enable object cache of the connected sheep daemon'
complete -c sheepfs -s p -l port -d 'specify the sheep port (default: 7000)'
complete -c sheepfs -s h -l help -d 'display this help and exit'

