# virtxend
# Autogenerated from man page /usr/share/man/man8/virtxend.8.gz
complete -c virtxend -s h -l help
complete -c virtxend -s d -l daemon
complete -c virtxend -s f -l config
complete -c virtxend -s p -l pid-file
complete -c virtxend -s t -l timeout
complete -c virtxend -s v -l verbose
complete -c virtxend -l version
complete -c virtxend -o rw-r--r--

